#!/usr/bin/env bash
set -euo pipefail

project_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build_dir="$project_dir/dist"

rm -rf "$build_dir"
mkdir -p "$build_dir/client" "$build_dir/server"

cp \
  "$project_dir/index.html" \
  "$project_dir/app.js" \
  "$project_dir/styles.css" \
  "$project_dir/manifest.webmanifest" \
  "$project_dir/sw.js" \
  "$project_dir/about.html" \
  "$project_dir/privacy.html" \
  "$project_dir/security.html" \
  "$project_dir/trust.css" \
  "$project_dir/robots.txt" \
  "$project_dir/sitemap.xml" \
  "$project_dir/icon.svg" \
  "$project_dir/icon-192.png" \
  "$project_dir/icon-512.png" \
  "$project_dir/icon-maskable-512.png" \
  "$project_dir/apple-touch-icon.png" \
  "$project_dir/og.png" \
  "$build_dir/client/"
mkdir -p "$build_dir/client/.well-known"
cp "$project_dir/.well-known/security.txt" "$build_dir/client/.well-known/security.txt"
cp -R "$project_dir/assets" "$build_dir/client/assets"
# The worker ships as ONE self-contained file. worker/sites.js imports the shared
# interpretation contract, but some hosts upload only the entry point — and because this
# worker also serves the static assets, a failed import would take the entire site down,
# not just /api. Inlining at build time removes that failure mode entirely.
# Edit worker/interpretation.js and worker/sites.js; never dist/server/index.js.
{
  printf '// GENERATED by scripts/build-sites.sh — do not edit.\n'
  printf '// Sources: worker/interpretation.js (inlined below) + worker/sites.js\n\n'
  sed 's/^export //' "$project_dir/worker/interpretation.js"
  printf '\n'
  sed '1,/^} from ".\/interpretation.js";$/d' "$project_dir/worker/sites.js"
} > "$build_dir/server/index.js"

printf 'Sites build ready: %s\n' "$build_dir"
